---
services:
  database:
    image: mysql:8.4
    container_name: vault-database
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - vault

  web:
    build:
      context: .
    container_name: vault-web
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.4&charset=utf8mb4
    depends_on:
      database:
       condition: service_healthy
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - var_data:/var/www/html/var
    ports:
      - "8080:80"
    networks:
    - vault

networks:
  vault:

volumes:
  database_data:
  vendor_data:
  var_data: